#!/usr/bin/rebol_core -qs
REBOL [;{{{ } } }
	Title:   "Coversion of a file containing GeolPDA orientations measurements"
	Date:    == 19-Oct-2013/10:52:07+2:00
	Version: 0.0.0 
	Purpose: {
		Conversion from a .csv file generated by GeolPDA,
		containing structural measurements expressed as 
		3x3 rotation matrices of the telephone orientation, 
		to a file containing "traditional" structural geological
		measurements, and fields necessary to be able to map
		structural symbols by using a GIS package.
	}
	History: [
	]
	License: {
This file is part of GeolLLibre software suite: FLOSS dedicated to Earth Sciences.
###########################################################################
##          ____  ___/_ ____  __   __   __   _()____   ____  _____       ##
##         / ___\/ ___// _  |/ /  / /  / /  /  _/ _ \ / __ \/ ___/       ##
##        / /___/ /_  / / | / /  / /  / /   / // /_/_/ /_/ / /_          ##
##       / /_/ / /___|  \/ / /__/ /__/ /___/ // /_/ / _, _/ /___         ##
##       \____/_____/ \___/_____/___/_____/__/_____/_/ |_/_____/         ##
##                                                                       ##
###########################################################################
  Copyright (C) 2013 Pierre Chevalier <pierrechevaliergeol@free.fr>
 
    GeolLLibre is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>
    or write to the Free Software Foundation, Inc., 51 Franklin Street, 
    Fifth Floor, Boston, MA 02110-1301, USA.
    See LICENSE file.
}
];}}}

; initialisation: ;{{{ } } }
if error? try [						; Récupération des routines (et des préférences) et connexion à la base
if error? try [						; Récupération des routines (et des préférences) et connexion à la base
do load to-file system/options/home/bin/gll_routines.r	; soit depuis ~/bin
] [
do load to-file %gll_routines.r				; ou sinon là où se trouve le script présent
]
] [
do load to-file system/options/home/geolllibre/gll_routines.r		; ou sinon dans ~/geolllibre
]

;}}}
; "import" these conversion tools:
;orientation: make object!...
;diagram: make object!...

; open geolpda .csv files:
file_in: to-file request-file/title/filter "GeolPDA orientations file" "Open" [geolpda*.csv *csv *.CSV]
; DEBUG
file_in: %geolllibre/geolpda_orientations.csv

; read its contents into a block! named orientations:
orientations: copy []
foreach line at read/lines file_in 2 [
	r: parse/all line ","		; r stands for row
	;print r
	; add fields to orientations:       _id poi_id orientationtype        rot1    rot2    rot3    rot4    rot5    rot6     rot7     rot8     rot9   v1 v2 v3
	;                                     1      2               3           4       5       6       7       8       9       10       11       12   13 14 15 16
	append/only orientations reduce   [ r/1    r/2             r/3 rejoin [r/4 " " r/5 " " r/6 " " r/7 " " r/8 " " r/9 " " r/10 " " r/11 " " r/12 ]]
]
;print mold orientations/1	;DEBUG
;>> print mold orientations/1;DEBUG
;["867" "372" "P" {0.113424 0.0507597 -0.992249 -0.0104283 0.9987 0.0498977 0.993492 0.00468783 0.113806}]

; iterate through orientations, and make another block! with the computed structural measurements:
struct_measures: copy []
foreach i orientations [
	o: orientation/new to-block to-string (at i 4)
	append struct_measures o
	;print o/print_plane_line
]

length? struct_measures
;== 867

;=> too dispendious to make so many object!s with the code repeated every time.


;DEBUG
i: orientations/1
o: orientation/new to-block to-string (at i 4)

l: layout [
	zone_diagram: box ivory 220x220 effect [
		grid 10x10
		;draw [circle 100 100 10]]
		]
	btn #"q" "quit"[unview]
]
append zone_diagram/effect/draw structural_symbol
view l


