#!/bin/sh
# Pierre Chevalier
# Ce script va prendre la sortie de sql2csv et va l'ouvrir direct dans oocalc

echo "$1"
sql2csv "$1" > /tmp/tmp_sql2csvpipeoocalc.csv && oocalc /tmp/tmp_sql2csvpipeoocalc.csv
#rm -I tmp_sql2csvpipeoocalc.csv

